import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';
import { createDatabase } from './database.mjs';

const migration = readFileSync(
  new URL('../migrations/20261003130000_profile_sport_workout_baseline.sql', import.meta.url),
  'utf8',
);

test('baseline creates signup profiles, isolates owners, and denies anonymous access', async () => {
  const db = await createDatabase();
  try {
    await db.exec('CREATE TABLE public.default_grant_probe (id integer);');
    assert.equal(
      (
        await db.query(
          "SELECT has_table_privilege('anon', 'public.default_grant_probe', 'SELECT') AS granted",
        )
      ).rows[0].granted,
      true,
    );
    assert.equal(
      (
        await db.query(
          "SELECT has_table_privilege('authenticated', 'public.default_grant_probe', 'DELETE') AS granted",
        )
      ).rows[0].granted,
      true,
    );
    await db.exec('DROP TABLE public.default_grant_probe');
    await db.exec(migration);
    assert.equal(
      (await db.query("SELECT has_table_privilege('anon', 'public.profile', 'SELECT') AS granted"))
        .rows[0].granted,
      false,
    );
    assert.equal(
      (
        await db.query(
          "SELECT has_table_privilege('authenticated', 'public.profile', 'DELETE') AS granted",
        )
      ).rows[0].granted,
      false,
    );
    assert.equal(
      (
        await db.query(
          "SELECT has_table_privilege('authenticated', 'public.sport', 'UPDATE') AS granted",
        )
      ).rows[0].granted,
      false,
    );
    assert.equal(
      (
        await db.query(
          "SELECT has_sequence_privilege('authenticated', 'public.sport_id_seq', 'USAGE') AS granted",
        )
      ).rows[0].granted,
      false,
    );

    const alice = '00000000-0000-4000-8000-000000000001';
    const bob = '00000000-0000-4000-8000-000000000002';
    await db.query('INSERT INTO auth.users (id, email) VALUES ($1, $2)', [
      alice,
      'alice@example.test',
    ]);
    await db.query('INSERT INTO auth.users (id, email) VALUES ($1, $2)', [bob, 'bob@example.test']);
    assert.deepEqual((await db.query('SELECT id, email FROM public.profile ORDER BY id')).rows, [
      { id: alice, email: 'alice@example.test' },
      { id: bob, email: 'bob@example.test' },
    ]);

    await db.exec(`INSERT INTO public.sport (name) VALUES ('Running');`);
    await db.exec(`SET ROLE authenticated; SET request.jwt.claim.sub = '${alice}';`);
    assert.equal(
      (await db.query('SELECT count(*)::int AS count FROM public.sport')).rows[0].count,
      1,
    );
    assert.deepEqual((await db.query('SELECT id FROM public.profile')).rows, [{ id: alice }]);
    await db.query("INSERT INTO public.workout (description) VALUES ('Alice run')");
    await db.exec(`SET request.jwt.claim.sub = '${bob}';`);
    assert.deepEqual((await db.query('SELECT description FROM public.workout')).rows, []);
    assert.equal(
      (
        await db.query(
          "UPDATE public.workout SET description = 'stolen' WHERE profile_id = $1 RETURNING id",
          [alice],
        )
      ).rows.length,
      0,
    );
    await db.exec('RESET ROLE');

    await db.exec('SET ROLE anon');
    await assert.rejects(db.query('SELECT * FROM public.profile'), /permission denied/);
    await assert.rejects(db.query('SELECT * FROM public.sport'), /permission denied/);
    await assert.rejects(db.query('SELECT * FROM public.workout'), /permission denied/);
    await assert.rejects(
      db.query(`SELECT public.handle_new_user()`),
      /permission denied for function handle_new_user/,
    );
    await db.exec('RESET ROLE');

    // Reapplying is safe and keeps the trigger and access model consistent.
    await db.exec(migration);
    assert.equal(
      (await db.query('SELECT count(*)::int AS count FROM public.profile')).rows[0].count,
      2,
    );
  } finally {
    await db.close();
  }
});

test('baseline repairs the existing schema and replaces the broken plural signup target', async () => {
  const db = await createDatabase();
  try {
    await db.exec(`
      CREATE TABLE public.profile (
        id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
        email text, username text, created_at timestamptz DEFAULT now(), preferences jsonb
      );
      CREATE TABLE public.sport (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name text, is_gym boolean NOT NULL DEFAULT false, metrics jsonb
      );
      CREATE TABLE public.workout (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        profile_id uuid NOT NULL DEFAULT auth.uid() REFERENCES public.profile(id),
        sport_id bigint REFERENCES public.sport(id) ON UPDATE CASCADE ON DELETE SET NULL,
        description text, date timestamptz, created_at timestamptz DEFAULT now(),
        completed boolean NOT NULL DEFAULT false, gym_exercises jsonb,
        metrics jsonb, parts jsonb, duration smallint NOT NULL DEFAULT 0
      );
      ALTER TABLE public.profile ENABLE ROW LEVEL SECURITY;
      ALTER TABLE public.sport ENABLE ROW LEVEL SECURITY;
      ALTER TABLE public.workout ENABLE ROW LEVEL SECURITY;
      CREATE POLICY old_profile_policy ON public.profile FOR ALL USING (true) WITH CHECK (true);
      CREATE POLICY old_workout_policy ON public.workout FOR ALL USING (true) WITH CHECK (true);
      GRANT ALL ON SEQUENCE public.sport_id_seq TO authenticated;
      CREATE FUNCTION public.handle_new_user() RETURNS trigger
        LANGUAGE plpgsql SECURITY DEFINER AS $$
        BEGIN
          INSERT INTO public.profiles (id, email) VALUES (NEW.id, NEW.email);
          RETURN NEW;
        END;
      $$;
      CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users
        FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
    `);

    // Existing user and workout data survive the additive migration.
    const existingUser = '00000000-0000-4000-8000-000000000010';
    await db.exec('ALTER TABLE auth.users DISABLE TRIGGER on_auth_user_created');
    await db.query('INSERT INTO auth.users (id, email) VALUES ($1, $2)', [
      existingUser,
      'existing@example.test',
    ]);
    await db.query('INSERT INTO public.profile (id, email) VALUES ($1, $2)', [
      existingUser,
      'existing@example.test',
    ]);
    await db.query(
      "INSERT INTO public.workout (profile_id, description) VALUES ($1, 'kept workout')",
      [existingUser],
    );
    await db.exec('ALTER TABLE auth.users ENABLE TRIGGER on_auth_user_created');

    await db.exec(migration);
    assert.equal(
      (
        await db.query(
          "SELECT has_sequence_privilege('authenticated', 'public.sport_id_seq', 'USAGE') AS granted",
        )
      ).rows[0].granted,
      false,
    );
    const newUser = '00000000-0000-4000-8000-000000000011';
    await db.query('INSERT INTO auth.users (id, email) VALUES ($1, $2)', [
      newUser,
      'new@example.test',
    ]);
    assert.deepEqual((await db.query('SELECT id, email FROM public.profile ORDER BY id')).rows, [
      { id: existingUser, email: 'existing@example.test' },
      { id: newUser, email: 'new@example.test' },
    ]);
    assert.deepEqual((await db.query('SELECT description FROM public.workout')).rows, [
      { description: 'kept workout' },
    ]);
    assert.equal(
      (
        await db.query(
          "SELECT count(*)::int AS count FROM pg_policies WHERE schemaname = 'public' AND tablename = 'profile' AND policyname = 'old_profile_policy'",
        )
      ).rows[0].count,
      0,
    );
  } finally {
    await db.close();
  }
});
