'use strict';
const slides=[...document.querySelectorAll('.slide')];
const deck=document.querySelector('#deck');
const viewport=document.querySelector('#viewport');
let current=0;
function resize(){deck.style.transform=`scale(${Math.min(viewport.clientWidth/1600,viewport.clientHeight/900)})`;}
function show(index){current=Math.max(0,Math.min(slides.length-1,index));slides.forEach((slide,i)=>{slide.hidden=i!==current;});document.querySelector('#counter').textContent=`${String(current+1).padStart(2,'0')} / ${slides.length}`;document.querySelector('#prev').disabled=current===0;document.querySelector('#next').disabled=current===slides.length-1;document.querySelectorAll('#dots button').forEach((button,i)=>button.setAttribute('aria-current',String(i===current)));document.querySelector('#notes-copy').textContent=slides[current].dataset.notes;history.replaceState(null,'',`#${current+1}`);}
slides.forEach((slide,i)=>{const dot=document.createElement('button');dot.setAttribute('aria-label',`Slajd ${i+1}: ${slide.dataset.title}`);dot.addEventListener('click',()=>show(i));document.querySelector('#dots').append(dot);const entry=document.createElement('button');const number=document.createElement('span');number.textContent=String(i+1).padStart(2,'0');entry.append(number,document.createTextNode(slide.dataset.title));entry.addEventListener('click',()=>{show(i);document.querySelector('#slide-picker').close();});document.querySelector('#picker-grid').append(entry);});
document.querySelector('#prev').addEventListener('click',()=>show(current-1));document.querySelector('#next').addEventListener('click',()=>show(current+1));
const picker=document.querySelector('#slide-picker');document.querySelector('#overview').addEventListener('click',()=>picker.showModal());document.querySelector('#close-picker').addEventListener('click',()=>picker.close());picker.addEventListener('click',event=>{if(event.target===picker){const r=picker.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)picker.close();}});
function toggleNotes(){const panel=document.querySelector('#notes-panel');panel.hidden=!panel.hidden;document.querySelector('#notes').setAttribute('aria-expanded',String(!panel.hidden));}
document.querySelector('#notes').setAttribute('aria-expanded','false');document.querySelector('#notes').addEventListener('click',toggleNotes);document.querySelector('#close-notes').addEventListener('click',toggleNotes);
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else document.querySelector('#fullscreen').textContent='Użyj pełnego ekranu przeglądarki';}catch{document.querySelector('#fullscreen').textContent='Użyj pełnego ekranu przeglądarki';}}
document.querySelector('#fullscreen').addEventListener('click',fullscreen);
document.addEventListener('keydown',event=>{if(picker.open||event.altKey||event.ctrlKey||event.metaKey||/INPUT|TEXTAREA|SELECT/.test(event.target.tagName))return;const key=event.key.toLowerCase();if(['arrowright','arrowleft','pagedown','pageup','home','end',' '].includes(key)){if(event.target.closest('button')&&key===' ')return;event.preventDefault();}if(['arrowright','pagedown',' '].includes(key))show(current+1);if(['arrowleft','pageup'].includes(key))show(current-1);if(key==='home')show(0);if(key==='end')show(slides.length-1);if(key==='f')fullscreen();if(key==='n')toggleNotes();if(key==='o')picker.showModal();if(key==='escape'){document.querySelector('#notes-panel').hidden=true;document.querySelector('#notes').setAttribute('aria-expanded','false');}});
let touchStart;viewport.addEventListener('touchstart',event=>{touchStart={x:event.changedTouches[0].clientX,y:event.changedTouches[0].clientY};},{passive:true});viewport.addEventListener('touchend',event=>{if(!touchStart)return;const dx=event.changedTouches[0].clientX-touchStart.x,dy=event.changedTouches[0].clientY-touchStart.y;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.5)show(current+(dx<0?1:-1));touchStart=null;},{passive:true});
const demos={start:{label:'Twój pierwszy tydzień',title:'20 minut ruchu w domu',description:'Spokojny początek, bez sprzętu. Pierwsza sesja w środę po pracy.',minutes:'20',days:['Środa · ruch w domu','Piątek · spokojny spacer'],message:'Zaczynamy od dwóch krótkich aktywności.'},short:{label:'Plan dopasowany do dzisiaj',title:'10 minut spokojnych ćwiczeń',description:'Skracamy sesję. Bez sprzętu i bez dokładania zaległości do kolejnego treningu.',minutes:'10',days:['Środa · krótszy ruch w domu','Piątek · spokojny spacer'],message:'Mniej czasu? Dzisiejszy krok też może być mniejszy.'},missed:{label:'Powrót po opuszczonym dniu',title:'15 minut na spokojny powrót',description:'Środa wypadła z planu. Kolejny krok to lekka aktywność w piątek.',minutes:'15',days:['Piątek · lekki ruch w domu','Niedziela · spacer, jeśli masz przestrzeń'],message:'Nie nadrabiamy wszystkiego naraz. Wracamy do wykonalnego planu.'}};
document.querySelectorAll('[data-demo]').forEach(button=>button.addEventListener('click',()=>{const item=demos[button.dataset.demo];for(const field of ['label','title','description','minutes','message'])document.querySelector(`#demo-${field}`).textContent=item[field];const days=document.querySelector('#demo-days');days.replaceChildren(...item.days.map(text=>{const span=document.createElement('span');span.textContent=text;return span;}));document.querySelectorAll('[data-demo]').forEach(other=>{other.classList.toggle('active',other===button);other.setAttribute('aria-pressed',String(other===button));});}));
function fromHash(){const value=Number(location.hash.slice(1));show(Number.isInteger(value)&&value>=1&&value<=slides.length?value-1:0);}
window.addEventListener('hashchange',fromHash);window.addEventListener('resize',resize);fromHash();resize();
