-- Baseline tables and client access for the existing hosted schema.
-- CREATE IF NOT EXISTS lets this apply over projects where these tables already exist.
BEGIN;

CREATE TABLE IF NOT EXISTS public.profile (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text,
  username text,
  created_at timestamptz DEFAULT now(),
  preferences jsonb
);

CREATE TABLE IF NOT EXISTS public.sport (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  is_gym boolean NOT NULL DEFAULT false,
  metrics jsonb
);

CREATE TABLE IF NOT EXISTS public.workout (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL DEFAULT auth.uid() REFERENCES public.profile(id),
  sport_id bigint REFERENCES public.sport(id) ON UPDATE CASCADE ON DELETE SET NULL,
  description text,
  date timestamptz,
  created_at timestamptz DEFAULT now(),
  completed boolean NOT NULL DEFAULT false,
  gym_exercises jsonb,
  metrics jsonb,
  parts jsonb,
  duration smallint NOT NULL DEFAULT 0
);

ALTER TABLE public.profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sport ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workout ENABLE ROW LEVEL SECURITY;

-- Remove prior policies on these tables so old permissive rules cannot broaden access.
DO $policies$
DECLARE
  policy_row record;
BEGIN
  FOR policy_row IN
    SELECT schemaname, tablename, policyname
    FROM pg_policies
    WHERE schemaname = 'public' AND tablename IN ('profile', 'sport', 'workout')
  LOOP
    EXECUTE format('DROP POLICY %I ON %I.%I', policy_row.policyname,
                   policy_row.schemaname, policy_row.tablename);
  END LOOP;
END
$policies$;

CREATE POLICY profile_owner_select ON public.profile
  FOR SELECT TO authenticated USING ((SELECT auth.uid()) = id);
CREATE POLICY profile_owner_insert ON public.profile
  FOR INSERT TO authenticated WITH CHECK ((SELECT auth.uid()) = id);
CREATE POLICY profile_owner_update ON public.profile
  FOR UPDATE TO authenticated USING ((SELECT auth.uid()) = id)
  WITH CHECK ((SELECT auth.uid()) = id);

CREATE POLICY sport_catalog_select ON public.sport
  FOR SELECT TO authenticated USING (true);

CREATE POLICY workout_owner_select ON public.workout
  FOR SELECT TO authenticated USING ((SELECT auth.uid()) = profile_id);
CREATE POLICY workout_owner_insert ON public.workout
  FOR INSERT TO authenticated WITH CHECK ((SELECT auth.uid()) = profile_id);
CREATE POLICY workout_owner_update ON public.workout
  FOR UPDATE TO authenticated USING ((SELECT auth.uid()) = profile_id)
  WITH CHECK ((SELECT auth.uid()) = profile_id);
CREATE POLICY workout_owner_delete ON public.workout
  FOR DELETE TO authenticated USING ((SELECT auth.uid()) = profile_id);

REVOKE ALL ON public.profile, public.sport, public.workout FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.sport_id_seq FROM PUBLIC, anon, authenticated;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.profile TO authenticated;
GRANT SELECT ON public.sport TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.workout TO authenticated;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
BEGIN
  INSERT INTO public.profile (id, email)
  VALUES (NEW.id, NEW.email)
  ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email;
  RETURN NEW;
END;
$function$;

REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM anon, authenticated;
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

COMMIT;
