-- Add 'Programowanie' to the sports catalog in public.sport.
-- Follows the contract schema: { key, label, unit, type, required, minimum }.

CREATE TABLE IF NOT EXISTS public.sport (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  is_gym boolean NOT NULL DEFAULT false,
  generation_enabled boolean NOT NULL DEFAULT true,
  metrics jsonb NOT NULL DEFAULT '[]'::jsonb
);

ALTER TABLE public.sport ADD COLUMN IF NOT EXISTS generation_enabled boolean NOT NULL DEFAULT true;

INSERT INTO public.sport (name, is_gym, generation_enabled, metrics)
VALUES (
  'Programowanie',
  false,
  true,
  '[
    {
      "key": "duration_minutes",
      "label": "Czas trwania",
      "unit": "min",
      "type": "number",
      "required": true,
      "minimum": 1
    },
    {
      "key": "lines_of_code",
      "label": "Linie kodu",
      "unit": "loc",
      "type": "number",
      "required": false,
      "minimum": 0
    },
    {
      "key": "caffeine_cups",
      "label": "Wypite kawy",
      "unit": "kubki",
      "type": "number",
      "required": false,
      "minimum": 0
    },
    {
      "key": "bugs_resolved",
      "label": "Rozwiązane bugi",
      "unit": "szt",
      "type": "number",
      "required": false,
      "minimum": 0
    }
  ]'::jsonb
);
